# Generated by Django 2.1.11 on 2019-08-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0007_slide_name_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='plugin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_link', to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='cms_page',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='cms_page',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page'),
        ),
    ]
