# Generated by Django 2.2.12 on 2020-05-08 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headers', '0002_header_cms_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='cms_page',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page'),
        ),
    ]
