# Generated by Django 2.1.11 on 2019-08-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_text_cms_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='cms_page',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page'),
        ),
    ]
