# Generated by Django 2.1.11 on 2019-08-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_auto_20170718_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='cms_page',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page'),
        ),
    ]
